# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: db01ff3cdabf6ba0f87a748aab2d03c26e60210a2fb9b99aa3f9b6f2817ae6222c21e6f963560facf30897ca8fa6b904fec51bbfecc3109c5a488784e0798bba

test:
  secret_key_base: 7bcb8232bad003ca60e41b89fa73b5ff083c66b94820c82a5300f8d3c53b8e697eb5ec984020792cbbb4b6f08821580ae57521b452cca3cac3bd172bba471671

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
